### ISSUE TITLE
請問可以在 nextjs6 中使用嗎?

### ISSUE THREAD

**Issue by imagine10255** [postor/next-i18n-helper#2]
請問可以在 nextjs6 中使用嗎?
目前在nextjs6 使用 i18next 有點問題,
不知道這個套件是否可以提供 nextjs6 的使用範例

**Comment by postor** [comment]
补充了next6的样例 ，见`next-i18n-helper/example-next6`，注意文件夹层级会有影响，请把`example-next6`拷贝到`next-i18n-helper`外面再安装依赖包
