### ISSUE TITLE
Default lanaguage is not working

### ISSUE THREAD

**Issue by daviddang91** [postor/next-i18n-helper#9]
I have changed the Chinese language as a default language, but it still using English as default.

`
export const i18nHelper = new I18nHelper({
  defaultLang: 'zh',
  supportLangs: ['en', 'zh']
})
`

**Comment by postor** [comment]
1st check your cookie
2nd check your broswer language
3rd defaultLanguage config

so maybe first two has alreay decided your language, I will add a new config `forceInitalLanguage` which go between 1st and 2nd later

**Comment by postor** [comment]
`forceInitalLanguage` added in `v1.0.31`
